import type {Metadata} from "next";
import {Bitcount_Single, Geist, Geist_Mono, Lexend_Zetta, Libre_Barcode_128} from "next/font/google";
import "../styles/globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const lexendZetta = Lexend_Zetta({
    variable: "--font-lexend-zetta",
    subsets: ["latin"],
});

const bitcountSingle = Bitcount_Single({
    variable: "--font-bitcount-single",
    subsets: ["latin"],
});

const libreBarcode39 = Libre_Barcode_128({
    variable: "--font-libre-barcode",
    subsets: ["latin"],
    weight: "400",
});



export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${bitcountSingle.variable} ${lexendZetta.variable} ${libreBarcode39.variable} antialiased`}
        >
        {children}
        </body>
        </html>
    );
}
