import type {Metadata} from "next";
import {Hanken_Grotesk, Lexend_Zetta, Libre_Barcode_128, Roboto_Mono} from "next/font/google";
import "../styles/globals.css";


const lexendZetta = Lexend_Zetta({
    variable: "--font-lexend-zetta",
    subsets: ["latin"],
});

const HankenGrotesk = Hanken_Grotesk({
    variable: "--font-hanken-grotesk",
    subsets: ["latin"],
    weight: ["200", "300", "400", "500", "600", "700"],
});

const RobotoMono = Roboto_Mono({
    variable: "--font-roboto-mono",
    subsets: ["latin"],
    weight: ["400", "700"],
});


const libreBarcode39 = Libre_Barcode_128({
    variable: "--font-libre-barcode",
    subsets: ["latin"],
    weight: "400",
});



export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${HankenGrotesk.variable} ${lexendZetta.variable} ${libreBarcode39.variable} ${RobotoMono.variable} antialiased overscroll-none overflow-hidden`}
        >
        {children}
        </body>
        </html>
    );
}
